### PR TITLE
Upgrade SBT and cross-compile to Scala 2.13

### PR DESCRIPTION
**Pull request by alonsodomin**
In order to support Scala 2.13, some upgrades to the dependencies had to be done too, i.e.: ScalaJS which had to upgraded to 1.0.0-M6. This will also give the option to those that want to move to ScalaJS 1.0.

To simplify the upgrade and not having to maintain different sources for each Scala version, I added Scala 2.13 collections compatibility dependency to the build, which may not be desired, so let me know your thoughts on that.

### CODE REVIEW

**Comment by alonsodomin** [comment]
Given that now Scala 2.13 is officilally out, would it be possible to get this merged/reviewed?

**Comment by nrinaudo** [comment]
Upvote, this is blocking me as well. Is there anything I can do to help?

**Comment by alonsodomin** [comment]
@nrinaudo you caught me at considering "stalking" @propensive in Twitter to see if I could get some of his attention...

The tests unfortunately don't run, seems that there is a missing dependency so was expecting that Jon could give some light on that... The main code seems to work, (tested locally) so I presume this just needs a review and a potential merge+release.

**Comment by alonsodomin** [comment]
...also, I probably went too far in upgrading ScalaJS to 1.0.0-M6, most likely it'd be better to downgrade it to 0.6.28

**Review by propensive — APPROVED** [review]

**Comment by propensive** [comment]
Thank you for this, @alonsodomin (and also @nrinaudo for hassling me about it!), and sorry I didn't notice until now.

**Comment by nrinaudo** [comment]
Of course, that was the easy bit - getting you to merge that PR. Now, we somehow have to get you to do a sonatype release :/

**Pull request merged**
