### PR TITLE
cleaner build

### PR DESCRIPTION
**Pull request by fommil**
I need to remove sbt-scalariform from sbt-sensible, as this currently reformats everything.

It would also be good to get a cleaner solution to https://github.com/scala-native/scala-native/issues/742 and especially something that better works around skipping native building on 2.10 and 2.12.

### CODE REVIEW

**Comment by fommil** [comment]
@dwijnand could you please have a look at this PR and see why when we do `++2.12.2` the `JS` projects are not removed. I thought doge would take care of that.

**Comment by fommil** [comment]
this is good to go, I think.

**Comment by fommil** [comment]
also, if you want to clean up / control your build files a little more, I recommend forking sbt-sensible and change `organization` in [the build.sbt](https://github.com/fommil/sbt-sensible/blob/master/build.sbt#L1), then go through the plugins it provides and cherry pick what you want to keep / remove, then add your own preferred defaults. 

Another example of a similar thing is https://github.com/cakesolutions/sbt-cake

**Comment by propensive** [comment]
@fommil Just to reassure you, I certainly haven't forgotten this, but I'm going to redevelop both the Contextual and [Magnolia](http://magnolia.work/) builds together.

**Comment by fommil** [comment]
we still need to work out how to skip the scala-native 2.10 and 2.12 builds :man_shrugging:

**Comment by fommil** [comment]
Closing... the history should remain though.

**Pull request closed without merging**
